name: Deploy Node-RED Flow

on:
  push:
    branches:
      - main   # chạy khi có push lên nhánh main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy flows to staging
        run: |
          scp -o StrictHostKeyChecking=no flows.json settings.js \
          03541@localhost:/C/Users/03541/.node-red/
